name: MultiModalFastM
use_tb_logger: true
model: MUCMTransformer

dataset:
  train:
    name: train
    noise_dataroot: ~/Documents/fusion-dataset/coco-dataset/
    filter:
    noise_trainpairs: data/noise_train_grid_data.txt
    batch_size: 16
    image_size: 224
    max_iter: 40
    iter_size: 1
    workers: 4
    train_name: train2017
    debug: true

    irvis_dataroot: ~/Documents/fusion-dataset/MSRS-main/
    infrare_name: train/ir/
    visible_name: train/vi/
    irvis_trainpairs: data/irvis_train_data.txt

  val:
    name: val
    dataroot: ~/Documents/fusion-dataset/MEFB-dataset
    batch_size: 1
    workers: 1
    input_name: input


network_G:
  in_nc: 3
  block_num: 2
  init: xavier
  hidden_channels: 128
  K: 4

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

logger:
  print_freq: 10
  save_checkpoint_freq: 5 #!!float 5e3

train:
  lr: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 20
  max_grad_clip: 20
  niter: 500000
  epoch: 200

  lr_steps: [80, 160, 180, 190]
  lr_gamma: 0.5

  val_freq: 3 #!!float 5e3
  kernel_freq: 1 #!!float 5e3
  manual_seed: 1
